### ISSUE TITLE
QuickDrawBadges

### ISSUE THREAD

**Issue by fou1100ouacus** [fou1100ouacus/Badges#1]

**Comment by Ayamohamed0101** [comment]
test

**Comment by fou1100ouacus** [comment]
[![](https://raw.githubusercontent.com/Ayamohamed0101/AyaMohamed/master/profile-summary-card-output/midnight_purple/0-profile-details.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)
[![](https://raw.githubusercontent.com/Ayamohamed0101/AyaMohamed/master/profile-summary-card-output/midnight_purple/1-repos-per-language.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards) [![](https://raw.githubusercontent.com/Ayamohamed0101/AyaMohamed/master/profile-summary-card-output/midnight_purple/2-most-commit-language.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)
[![](https://raw.githubusercontent.com/Ayamohamed0101/AyaMohamed/master/profile-summary-card-output/midnight_purple/3-stats.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards) [![](https://raw.githubusercontent.com/Ayamohamed0101/AyaMohamed/master/profile-summary-card-output/midnight_purple/4-productive-time.svg)](https://github.com/vn7n24fzkq/github-profile-summary-cards)
